LOGGER: True
SEED: 42
DEBUG: False
QUANT: False
USE_PAST_KEY: True
PRIVATE: True

n_repetitions: 19 # Original notebook had 22 but times out :(
TOTAL_TOKENS: 2048 # if PRIVATE else 512

DEEP: True


temperature: 0.9
top_p: 1.0


